"""baseline

Revision ID: 21c227494aae
Revises: 
Create Date: 2026-04-22 07:58:25.592318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '21c227494aae'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('csm_meetings')
    op.drop_index(op.f('idx_announcements_active'), table_name='announcements')
    op.drop_table('announcements')
    op.drop_index(op.f('idx_member_roles_active'), table_name='member_roles')
    op.drop_index(op.f('idx_member_roles_member'), table_name='member_roles')
    op.drop_table('member_roles')
    op.drop_index(op.f('idx_imports_chapter'), table_name='data_imports')
    op.drop_index(op.f('idx_imports_status'), table_name='data_imports')
    op.drop_table('data_imports')
    op.drop_index(op.f('idx_palms_member'), table_name='palms_snapshots')
    op.drop_index(op.f('idx_palms_period'), table_name='palms_snapshots')
    op.drop_table('palms_snapshots')
    op.drop_index(op.f('idx_reviews_member'), table_name='member_reviews')
    op.drop_index(op.f('idx_reviews_status'), table_name='member_reviews')
    op.drop_table('member_reviews')
    op.drop_index(op.f('idx_meeting_activity_meeting'), table_name='meeting_activity')
    op.drop_index(op.f('idx_meeting_activity_member'), table_name='meeting_activity')
    op.drop_table('meeting_activity')
    op.drop_index(op.f('idx_referral_needs_member'), table_name='referral_needs')
    op.drop_table('referral_needs')
    op.drop_index(op.f('idx_presentations_member'), table_name='member_presentations')
    op.drop_table('member_presentations')
    op.drop_index(op.f('idx_achievements_member'), table_name='member_achievements')
    op.drop_index(op.f('idx_achievements_unannounced'), table_name='member_achievements', postgresql_where='(announced_at IS NULL)')
    op.drop_table('member_achievements')
    op.drop_index(op.f('idx_chapter_content'), table_name='chapter_content')
    op.drop_table('chapter_content')
    op.drop_index(op.f('idx_sponsorships_sponsor'), table_name='sponsorships')
    op.drop_table('sponsorships')
    op.drop_table('chapter_targets')
    op.drop_index(op.f('idx_action_items_csm'), table_name='action_items')
    op.drop_index(op.f('idx_action_items_status'), table_name='action_items')
    op.drop_table('action_items')
    op.add_column('chapters', sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('chapters', 'settings')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapters', sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('chapters', 'config')
    op.create_table('action_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('csm_meeting_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('chapter_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('assigned_to_member_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('assigned_to_name', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('due_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'open'::character varying"), autoincrement=False, nullable=True),
    sa.Column('completed_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint("status::text = ANY (ARRAY['open'::character varying, 'in_progress'::character varying, 'completed'::character varying, 'overdue'::character varying, 'cancelled'::character varying]::text[])", name=op.f('action_items_status_check')),
    sa.ForeignKeyConstraint(['csm_meeting_id'], ['csm_meetings.id'], name=op.f('action_items_csm_meeting_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('action_items_pkey'))
    )
    op.create_index(op.f('idx_action_items_status'), 'action_items', ['status'], unique=False)
    op.create_index(op.f('idx_action_items_csm'), 'action_items', ['csm_meeting_id'], unique=False)
    op.create_table('chapter_targets',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('chapter_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('period_label', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('period_start', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('period_end', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('metric', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('target_value', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint("metric::text = ANY (ARRAY['chapter_size'::character varying, 'attendance_rate'::character varying, 'referrals'::character varying, 'one_to_ones'::character varying, 'visitors'::character varying, 'ceu'::character varying, 'tyfcb'::character varying, 'member_growth'::character varying, 'retention'::character varying, 'conversion'::character varying]::text[])", name=op.f('chapter_targets_metric_check')),
    sa.PrimaryKeyConstraint('id', name=op.f('chapter_targets_pkey')),
    sa.UniqueConstraint('chapter_id', 'period_start', 'period_end', 'metric', name=op.f('chapter_targets_chapter_id_period_start_period_end_metric_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('sponsorships',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('chapter_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sponsor_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sponsored_member_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('sponsored_name', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('sponsor_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'active'::character varying"), autoincrement=False, nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint("status::text = ANY (ARRAY['active'::character varying, 'resigned'::character varying, 'terminated'::character varying]::text[])", name=op.f('sponsorships_status_check')),
    sa.PrimaryKeyConstraint('id', name=op.f('sponsorships_pkey'))
    )
    op.create_index(op.f('idx_sponsorships_sponsor'), 'sponsorships', ['sponsor_id'], unique=False)
    op.create_table('chapter_content',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('chapter_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('content_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint("content_type::text = ANY (ARRAY['core_values'::character varying, 'closing_quote'::character varying, 'branding'::character varying, 'networking_info'::character varying, 'president_intro'::character varying, 'vision_mission'::character varying, 'custom'::character varying]::text[])", name=op.f('chapter_content_content_type_check')),
    sa.PrimaryKeyConstraint('id', name=op.f('chapter_content_pkey'))
    )
    op.create_index(op.f('idx_chapter_content'), 'chapter_content', ['chapter_id', 'content_type'], unique=False)
    op.create_table('member_achievements',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('chapter_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('member_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('achievement_type', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('criteria_snapshot', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('achieved_at', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('announced_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('announced_meeting_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint("achievement_type::text = ANY (ARRAY['silver_member'::character varying, 'gold_member'::character varying, 'platinum_member'::character varying, 'palladium_member'::character varying, 'diamond_member'::character varying, 'green_member'::character varying, 'notable_networker'::character varying, 'top_referral'::character varying, 'top_tyfcb'::character varying, 'top_121'::character varying, 'top_visitor'::character varying, 'custom'::character varying]::text[])", name=op.f('member_achievements_achievement_type_check')),
    sa.PrimaryKeyConstraint('id', name=op.f('member_achievements_pkey'))
    )
    op.create_index(op.f('idx_achievements_unannounced'), 'member_achievements', ['announced_at'], unique=False, postgresql_where='(announced_at IS NULL)')
    op.create_index(op.f('idx_achievements_member'), 'member_achievements', ['member_id'], unique=False)
    op.create_table('member_presentations',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('member_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('focus_product', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('products_services', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('looking_for', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('product_images', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('rotation_order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint('version >= 1 AND version <= 4', name=op.f('member_presentations_version_check')),
    sa.PrimaryKeyConstraint('id', name=op.f('member_presentations_pkey')),
    sa.UniqueConstraint('member_id', 'version', name=op.f('member_presentations_member_id_version_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_presentations_member'), 'member_presentations', ['member_id'], unique=False)
    op.create_table('referral_needs',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('member_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('target_description', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('priority', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'active'::character varying"), autoincrement=False, nullable=True),
    sa.Column('version', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('fulfilled_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint("status::text = ANY (ARRAY['active'::character varying, 'fulfilled'::character varying, 'paused'::character varying, 'archived'::character varying]::text[])", name=op.f('referral_needs_status_check')),
    sa.CheckConstraint('priority >= 1 AND priority <= 5', name=op.f('referral_needs_priority_check')),
    sa.PrimaryKeyConstraint('id', name=op.f('referral_needs_pkey'))
    )
    op.create_index(op.f('idx_referral_needs_member'), 'referral_needs', ['member_id'], unique=False)
    op.create_table('meeting_activity',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('meeting_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('member_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('referrals_given', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('referrals_received', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('referrals_outside', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('tyfcb_amount', sa.NUMERIC(precision=15, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('one_to_ones', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('visitors_brought', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('ceu_credits', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('testimonials_given', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(length=30), server_default=sa.text("'manual'::character varying"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint("source::text = ANY (ARRAY['manual'::character varying, 'bot'::character varying, 'upload'::character varying, 'bni_connect'::character varying, 'zoom_parse'::character varying]::text[])", name=op.f('meeting_activity_source_check')),
    sa.PrimaryKeyConstraint('id', name=op.f('meeting_activity_pkey')),
    sa.UniqueConstraint('meeting_id', 'member_id', name=op.f('meeting_activity_meeting_id_member_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_meeting_activity_member'), 'meeting_activity', ['member_id'], unique=False)
    op.create_index(op.f('idx_meeting_activity_meeting'), 'meeting_activity', ['meeting_id'], unique=False)
    op.create_table('member_reviews',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('chapter_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('member_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('review_cycle', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('scheduled_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('actual_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('pic_member_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('score_percentage', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('keterangan', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('solusi', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'scheduled'::character varying"), autoincrement=False, nullable=True),
    sa.Column('decision', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint("decision::text = ANY (ARRAY['renew'::character varying, 'conditional'::character varying, 'exit'::character varying, NULL::character varying]::text[])", name=op.f('member_reviews_decision_check')),
    sa.CheckConstraint("status::text = ANY (ARRAY['scheduled'::character varying, 'completed'::character varying, 'overdue'::character varying, 'waived'::character varying, 'cancelled'::character varying]::text[])", name=op.f('member_reviews_status_check')),
    sa.CheckConstraint('review_cycle = ANY (ARRAY[1, 2])', name=op.f('member_reviews_review_cycle_check')),
    sa.CheckConstraint('score_percentage >= 0 AND score_percentage <= 100', name=op.f('member_reviews_score_percentage_check')),
    sa.PrimaryKeyConstraint('id', name=op.f('member_reviews_pkey'))
    )
    op.create_index(op.f('idx_reviews_status'), 'member_reviews', ['status'], unique=False)
    op.create_index(op.f('idx_reviews_member'), 'member_reviews', ['member_id'], unique=False)
    op.create_table('palms_snapshots',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('chapter_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('member_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('period_label', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('period_start', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('period_end', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('present_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('absent_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('medical_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('late_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('substitute_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('referrals_given', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('referrals_received', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('referrals_outside', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('visitors_brought', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('one_to_ones', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('tyfcb_amount', sa.NUMERIC(precision=15, scale=2), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('ceu_credits', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('import_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('palms_snapshots_pkey')),
    sa.UniqueConstraint('chapter_id', 'member_id', 'period_start', 'period_end', name=op.f('palms_snapshots_chapter_id_member_id_period_start_period_en_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_palms_period'), 'palms_snapshots', ['period_start', 'period_end'], unique=False)
    op.create_index(op.f('idx_palms_member'), 'palms_snapshots', ['member_id'], unique=False)
    op.create_table('data_imports',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('chapter_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('source_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('mapped_data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('import_status', sa.VARCHAR(length=20), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=True),
    sa.Column('records_total', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('records_imported', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('records_skipped', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('records_error', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('error_log', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('imported_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.CheckConstraint("import_status::text = ANY (ARRAY['pending'::character varying, 'processing'::character varying, 'completed'::character varying, 'partial'::character varying, 'failed'::character varying]::text[])", name=op.f('data_imports_import_status_check')),
    sa.CheckConstraint("source_type::text = ANY (ARRAY['roster_report'::character varying, 'palms_summary'::character varying, 'vp_report'::character varying, 'palms_attendance'::character varying, 'sponsor_report'::character varying, 'dues_report'::character varying, 'power_team_form'::character varying, 'attendance_sheet'::character varying, '7month_review'::character varying, 'csm_minutes'::character varying, 'google_sheet_sync'::character varying, 'manual_entry'::character varying, 'bot_webhook'::character varying, 'zoom_log'::character varying, 'other'::character varying]::text[])", name=op.f('data_imports_source_type_check')),
    sa.PrimaryKeyConstraint('id', name=op.f('data_imports_pkey'))
    )
    op.create_index(op.f('idx_imports_status'), 'data_imports', ['import_status'], unique=False)
    op.create_index(op.f('idx_imports_chapter'), 'data_imports', ['chapter_id'], unique=False)
    op.create_table('member_roles',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('member_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('chapter_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('committee', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('term_start', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('term_end', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint("role::text = ANY (ARRAY['president'::character varying, 'vice_president'::character varying, 'secretary'::character varying, 'treasurer'::character varying, 'secretary_treasurer'::character varying, 'gdc'::character varying, 'ambassador'::character varying, 'visitor_host'::character varying, 'education_coordinator'::character varying, 'events_coordinator'::character varying, 'mc_coordinator'::character varying, 'mentor_coordinator'::character varying, 'growth_coordinator'::character varying, 'mc_qa'::character varying, 'mc_cb'::character varying, 'mc_me'::character varying, 'mc_mr'::character varying, 'social_media_coordinator'::character varying, 'connect_coordinator'::character varying, 'one_to_one_coordinator'::character varying, 'go_green_coordinator'::character varying, 'feature_presentation_coordinator'::character varying, 'member'::character varying]::text[])", name=op.f('member_roles_role_check')),
    sa.PrimaryKeyConstraint('id', name=op.f('member_roles_pkey'))
    )
    op.create_index(op.f('idx_member_roles_member'), 'member_roles', ['member_id'], unique=False)
    op.create_index(op.f('idx_member_roles_active'), 'member_roles', ['is_active', 'chapter_id'], unique=False)
    op.create_table('announcements',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('chapter_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('meeting_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('priority', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=30), server_default=sa.text("'general'::character varying"), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.DATE(), server_default=sa.text('CURRENT_DATE'), autoincrement=False, nullable=True),
    sa.Column('expire_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint("type::text = ANY (ARRAY['general'::character varying, 'event'::character varying, 'renewal_reminder'::character varying, 'orientation'::character varying, 'visitor_day'::character varying, 'training'::character varying, 'achievement'::character varying, 'custom'::character varying]::text[])", name=op.f('announcements_type_check')),
    sa.CheckConstraint('priority >= 1 AND priority <= 5', name=op.f('announcements_priority_check')),
    sa.PrimaryKeyConstraint('id', name=op.f('announcements_pkey'))
    )
    op.create_index(op.f('idx_announcements_active'), 'announcements', ['is_active', 'start_date', 'expire_date'], unique=False)
    op.create_table('csm_meetings',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('chapter_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('location', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('attendees', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('agenda', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('vp_report', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('visitor_report', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('mc_report', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('education_report', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('mentor_report', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('event_report', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('next_meeting_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('csm_meetings_pkey'))
    )
    # ### end Alembic commands ###
